version: 2.1

orbs:
  sage:
    executors:
      node-10:
        docker:
          - image: 'circleci/node:10-stretch'
      php-73:
        docker:
          - image: 'circleci/php:7.3-stretch'
      php-72:
        docker:
          - image: 'circleci/php:7.2-stretch'
      php-71:
        docker:
          - image: 'circleci/php:7.1-stretch'
    jobs:
      build-php:
        parameters:
          executor:
            type: executor
        executor: << parameters.executor >>
        steps:
          - run: php -v
          - checkout
          - restore_cache:
              keys:
                - composer-v1-{{ checksum "composer.lock" }}
                - composer-v1-
          - run: composer install -n --prefer-dist
          - run: composer lint
          - save_cache:
              key: composer-v1-{{ checksum "composer.lock" }}
              paths:
                - vendor
      build-node:
        executor: node-10
        steps:
          - run: yarn versions
          - checkout
          - restore_cache:
              keys:
                - node-v1-{{ checksum "yarn.lock" }}
                - node-v1-
          - run: yarn install --frozen-lockfile
          - run: yarn run test
          - run: yarn run build:production
          - save_cache:
              key: node-v1-{{ checksum "yarn.lock" }}
              paths:
                - node_modules

workflows:
  build:
    jobs:
      - sage/build-node
      - sage/build-php:
          name: build-php-73
          executor: sage/php-73
      - sage/build-php:
          name: build-php-72
          executor: sage/php-72
      - sage/build-php:
          name: build-php-71
          executor: sage/php-71
