version: 2
jobs:
  build-php73:
    docker:
      - image: rootsdev/ubuntu18.04-php7.3-composer-nvm-yarn:0.0.1
    steps:
      - checkout
      - run: yarn test && yarn build && yarn build:production && composer test
  build-php72:
    docker:
      - image: rootsdev/ubuntu18.04-php7.2-composer-nvm-yarn:0.0.1
    steps:
      - checkout
      - run: yarn test && yarn build && yarn build:production && composer test
  build-php71:
    docker:
      - image: rootsdev/ubuntu18.04-php7.1-composer-nvm-yarn:0.0.1
    steps:
      - checkout
      - run: yarn test && yarn build && yarn build:production && composer test

workflows:
  version: 2
  build:
    jobs:
      - build-php73
      - build-php72
      - build-php71
