version: 2.1

orbs:
  node: circleci/node@3
  php: circleci/php@1

workflows:
  build:
    jobs:
      - node/test:
          name: node-<< matrix.version >>
          pkg-manager: yarn
          post-steps:
            - run: yarn run build:production
          matrix:
            parameters:
              version: ['10.21', '12.18', '14.4']
      - php/test:
          name: php-<< matrix.version >>
          test-command: lint
          matrix:
            parameters:
              version: ['7.2', '7.3', '7.4']
